### PR TITLE
forgot some code

### PR DESCRIPTION
**Pull request by DMMaster636**
so the stressed dodge plays when pressing space

### CODE REVIEW

**Comment by DMMaster636** [comment]
I might as well apply the stressed dodge to also pico and so

**Comment by DMMaster636** [comment]
it seems like the fla does not contain the new dodge anim for BF... so this might take a bit longer

**Comment by DMMaster636** [comment]
> It's ok we have time for everything so take your time, also thank you but thank you very much for being our artist I always wanted a good hd artist, this was my biggest dream, really thank you :) (Also good coder lol)

thanks and np dude, i just try to help as much as i can ;)

**Comment by DMMaster636** [comment]
p sure it's all done now
dodge offset could need a bit of work, but i'm gonna let you handle that
also, theoretically bf-pico could be removed, but again, i'm gonna let you handle that

**Comment by Nuno-Filipe-Studios** [comment]
> p sure it's all done now dodge offset could need a bit of work, but i'm gonna let you handle that also, theoretically bf-pico could be removed, but again, i'm gonna let you handle that

Ok, i'm going to test it later

**Comment by DMMaster636** [comment]
> Ok, i'm going to test it later, also, van you update the letter M in the combo sprite please? The rest of the sprite looks good

alright

**Comment by DMMaster636** [comment]
i made it so combo only appears after a certain amount of combos (cus that's the point of combos)

**Pull request merged**
