### PR TITLE
a few changes

### PR DESCRIPTION
**Pull request by DMMaster636**
this is a wip, do not merge yet
* use only 2 states instead of 8 for the henchmen
* edit some curStep and curBeat stuff
* lots of bf car + milf edits + fla for new milf idle (by me)
* hd combo sprite

### CODE REVIEW

**Comment by Nuno-Filipe-Studios** [comment]
I needed a new code because the other was messy, but yes thanks, really good :)

**Comment by DMMaster636** [comment]
> I needed a new code because the other was messy, but yes thanks, really good :)

thanks!
also, about the HD BF Car thing:
image
currently remaking the idle as the one in the fla is the old one (and after searching, the new one is in no fla)

**Comment by Nuno-Filipe-Studios** [comment]
> > I needed a new code because the other was messy, but yes thanks, really good :)
> 
> thanks! also, about the HD BF Car thing: image currently remaking the idle as the one in the fla is the old one (and after searching, the new one is in no fla)



> > I needed a new code because the other was messy, but yes thanks, really good :)
> 
> thanks! also, about the HD BF Car thing: image currently remaking the idle as the one in the fla is the old one (and after searching, the new one is in no fla)
>
> Yeah I know, koslan didn't add the new updated version of the flas, but, you made that new bf milf?

**Comment by DMMaster636** [comment]
> Yeah I know, koslan didn't add the new updated version of the flas, but, you made that new bf milf?

yep, now included in the newest commit
now i will edit some code, since after checking, some options don't work as intended

**Comment by DMMaster636** [comment]
after checking, my problem seemed to be clientside, dunno why, but idc
going to check one more thing, then this is good to go

**Comment by Nuno-Filipe-Studios** [comment]
> after checking, my problem seemed to be clientside, dunno why, but idc going to check one more thing, then this is good to go

What's a clientside?

**Comment by DMMaster636** [comment]
> What's a clientside?

stuff that happens to the user that doesn't happen to other people

**Comment by DMMaster636** [comment]
alright, pr is now ready to go

**Pull request merged**
